game/static/game/js/game.js

Noticed on the traffic lights behaviour: we were not resetting the game after every attempt.
The traffic lights were stale after the first try, and did not move any more.
Now, "reset" is called within "onStopControls".
This ensures the game goes back to the initial state after every attempt.
I have tested it quickly in a couple of levels.
Let me know if this could be an issue.

Reset game every time we stop the animation

---

game/static/game/js/model.js

The animation loses a blank step (introduced by calling incrementTime twice: once within incrementMovementTime and another one explicitly).
That blank step made the Step functionality appear as broken when the van crashes (as it required 2 clicks for the popup to appear).
The blank step has been removed, which means all animations in which the van crashes will lose 1 wait time (~ 500ms).
Should I introduce the wait as an animation, or it's ok to lose that step?
Fixes #614

Avoid blank animation steps

---

game/migrations/0057_workspace_language_enabled.py
game/models.py
game/static/game/js/game.js
game/static/game/js/level_editor.js
game/views/level.py

A "python" workspace can't be loaded in a "blockly level" anymore. Also, you cannot overwrite an incompatible workspace.
This will only work for "new style" workspaces (I changed the model). Old workspaces will still show.
To Do: make it work for old workspaces, and improve the ux: add indication about: which level it was saved in, the date of creation, ... ?

Cannot load incompatible workspace - wip

---

example_project/example_project/settings.py

For local development use the console email backend instead of generating real emails.
This will avoid spamming others, and make registering local users easier.

Use the console email backend. Fixes #744

---

.travis.yml

xgettext 0.18.1 doesn't deal with strings concatenated with +
Precise only has 0.18.1, so by switching to trusty we get
0.18.3, which supports our strings.

Switch to trusty beta infrastructure. Fixes #754

---

game/static/game/js/messages.js

Stops a 404 error when following the log-in link from the level editor.

Use django-reverse-js in messages.js

---

game/static/game/js/sound.js

After fix I've tested "Mute" button in Firefox under Debian Linux on two levels and Blockly sounds are muted now.

Fix for #802

---

game/end_to_end_tests/game_page.py

To test if the score earned at the end of a level is equal to the score passed in as an argument:
- Before: the test checked if the score string (of format x/10) **started with** the argument score x. This was flawed as there could be cases where the test would succeed unexpectedly 
ie: score string = "10/10", argument score = 1.
- Now: the score string is split at character '/'. The substring before is compared to the argument score and if the two are **equal**, the test succeeds.
Coverage: decreased by 0.09% because of random_road.py which has not been edited in this pull request.

Improved assert_score function.

---

game/static/game/js/game.js

Instead of just checking if user is a teacher, also check if the level is one of the official RR levels. If not, the solve button isn't created.
Coverage increased by 0.7%.

No more solve button for custom levels.

---

game/end_to_end_tests/base_game_test.py
game/end_to_end_tests/data/blockly_solutions/not_delivered_everywhere.xml
game/end_to_end_tests/data/blockly_solutions/running_a_red_light.xml
game/end_to_end_tests/data/blockly_solutions/running_out_of_fuel.xml
game/end_to_end_tests/data/blockly_solutions/running_out_of_instructions.xml
game/end_to_end_tests/data/blockly_solutions/undefined_procedure.xml
game/end_to_end_tests/game_page.py
game/end_to_end_tests/test_level_failures.py

Added tests which make sure blockly levels fail when:
- the van runs out of fuel
- the van runs out of instructions
- the van runs a red light
- the van doesn't deliver to every destination
- a procedure is undefined in blockly

Testing level failures

---

game/static/game/js/blocklyCompiler.js

The order of fields may be different depending on the translation. The reason:
"In Blockly for Web, if all of the human readable strings share the some prefix or suffix, those strings will extracted as a label before or after the drop down. This allows the prefix/suffix label place to adapt to language conventions. This feature will be ported to Android in the near future."
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#drop-down_field

Fixes #820

---

game/end_to_end_tests/base_game_test.py

Timeout value was too low, causing random tests to timeout before actually running.

Selenium tests timeout fix

---

game/admin.py

The Level model's owner foreign key caused the page loading to time out by trying to load all values in a select dropdown. This field is now readonly.

Makes Levels accessible on admin page

---

game/tests/test_scoreboard.py
game/views/level_selection.py

Trying to load the scoreboard page was causing a 500 error. Added the name attribute back to the episode data to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/992)

Fix scoreboard loading issue

---

game/end_to_end_tests/test_play_through.py
game/migrations/0068_fix_episodes_order.py

- Added a migration which swaps the contents of episodes 7 and 8 in the database tables.
- Changed the order of the episodes in the tests to reflect this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1004)

Fixes episodes order

---

game/migrations/0069_remove_user_levels_from_episodes.py
game/tests/migrations/test_migration_fix_episodes_order.py

Edited migration 69 to go through episodes 7 and 8's levels, pick the ones that have the right name *as well as* no associated owner (this means it was created by us) and add it to a new list. The new list of original levels only replaces the current content of the episodes to fix the current issue.
Since this migration wasn't applied to production in the latest deployment, simply editing it is enough instead of having to create a new one - I have tested this locally to make sure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1006)

Removes user levels from episodes

---

game/static/game/css/scoreboard.css
game/templates/game/scoreboard.html

- Removed the default 'invisible' setting of the tableWrapper class in CSS.
- Removed the JS line which makes it visible upon document load - which was probably not working well enough on production.
- Now, the scoreboard works normally since, when no data is selected, the scoreboard doesn't have anything to show, and when data is selected, it is by default visible and shows the appropriate data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1010)

Makes scoreboard visible when data is selected

---

.travis.yml

The config line to deploy to Semaphore had been removed by mistake, so this PR is adding it back in. It has been put after the success of the deploy stage.
The success of this can only be checked once this PR has been merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1021)

fix(.travis.yml): reinstate Semaphore curl request

---

example_project/example_project/settings.py
example_project/example_project/urls.py
test_settings.py

We're adding URLs to the example project to make the URLs consistent throughout the projects.
This has been tested by running the tests locally and successfully checking that the URLs were the correct ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1023)

refactor: Make URLs consistent with deployed project

---

setup.py

BREAKING CHANGE: this will temporarily break codeforlife-portal and deployment as it will be expecting an older version of the django rest framework
Upgrade django rest framework to the latest version we can have with our current Django version
By existing tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1029)

build: Upgrade django rest framework to 3.6.x

---

.travis.yml

Now that portal is on Django 1.10, we can use the default branch (master) of portal to run our tests against
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1033)

fix: Make travis point to codeforlife-portal’s default branch

---

game/tests/test_level_editor.py
game/views/level.py
game/views/level_editor.py

Using Django's `model_to_dict` function stopped working after the Django 1.10 upgrade, as such we've replaced it with Django Rest Framework's serializer.
A Unit test has been added to test when a user loads a level in the game editor. It's been checked to pass after the changes, and fail before the changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1036)

fix: Uses serializer to load level in editor

---

game/static/game/js/blocklyControl.js
game/static/game/js/blocklyCustomisations.js

This PR adds a Blockly Event so that the workspace code runs when the user clicks the Start block.
This was necessary as the Blockly library was updated in #1042. 
The event listener listens for a event of type click, and it checks that the block that is clicked is the Start block. If it is, the listener triggers a click on the Play button, which runs the program.
NB: The line which adds the event listener to the Start block inside the `reset` method was removed as it was redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1046)

fix: add Blockly event to run program on Start Block click

---

README.md
game/static/game/js/drawing.js

This change fixes a bug where it was possible to pan the game map by clicking on the green side menu. This fixes the issue #1048
This change also includes a documentation update to include some troubleshooting for setting up the project for MacOS Mojave users.
This has been tested manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1047)

Fix drag map from menu

---

game/templates/game/base.html
game/templates/game/basenonav.html

This PR fixes the incorrect link to the AI:MMO home page from the RR project for preview access users.
The fix was to entirely remove the `secondaryButtons` section as it did not need to be here. This makes the RR `base` inherit the `secondaryButtons` section from the portal base directly without unnecessarily overriding it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1049)

fix: remove secondary buttons block to extend directly from portal

---

.travis.yml

This PR installs the master branch of portal instead of the now deleted upgrade to Django 1.11 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1071)

fix: Install master branch of portal

---

.travis.yml
Pipfile
Pipfile.lock
game/end_to_end_tests/editor_page.py
game/end_to_end_tests/game_page.py
setup.py

Removed the dependency `docutils`, which isn't used. Fixed versions for `more-itertools` and `pytest` for Python 2.7 compatibillity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1073)

fix: removed docutils

---

Pipfile.lock
setup.py

This PR removes django-appconf as it is not used.
Ran tests locally and they all pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1076)

fix: Remove django-appconf

---

Pipfile.lock
game/tests/test_level_editor.py
game/tests/test_level_moderation.py
setup.py

This PR removes django-casper from the dependencies.
Ran tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1080)

fix: Remove django-casper

---

game/autoconfig.py
game/static/game/sass/game.scss
setup.py

Removed foundation icons and statics as they seem to be unused dead code
- Visually, manually tested
- Ran tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1083)

fix: remove Django foundation icons

---

game/end_to_end_tests/editor_page.py
game/end_to_end_tests/test_level_editor.py
game/random_road.py
game/templates/game/level_editor.html
game/tests/test_random_road.py
game/views/level_editor.py

This PR fixes the bug whereby the blocks would not appear properly in the level editor.
Manually, and a test has also been added to make sure the HTML elements are loaded properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1093)

fix: Invisible blocks bug

---

Dockerfile

f-string syntax is only valid in Python 3 but Dockerfile was using Python 2.
Added a shasum in case the image tag gets updated and breaks things
Fixes #1105  
I ran `docker-compose up` locally and checked localhost:8000 opened the site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1111)

fix: Use Python 3 in Dockerfile (#1105)

---

game/messages.py

fixes #705 The messages for Level 39 are updated in accordance with https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/705#issuecomment-643151943.   
Test suite still runs, visual inspection of messages.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ / ] I have linked this PR to a Zenhub Issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1129)

fix: Messages for Level 39 so that students are not encouraged to use if

---

.github/workflows/ci.yml
.github/workflows/publish-python-package.yml

I have also neatened up the GitHub actions ci.yml file so that the job has a more semantic name and won't run on "semantic-release" commits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1139)

fix: Use correct token for publishing packages

---

.github/workflows/publish-python-package.yml

In Publish action, "Run Crowdin" step will download translations in a docker container which runs as root. We need to update these permissions to the current user to be able to use translations in the next step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1149)

fix: fix translation files owner

---

game/messages.py

Replace links to youtube.com with youtube-nocookie.com to avoid targeting cookies.
Checked embedded YouTube videos still work in rapid-router levels 19, 29, 33, 36 and 44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1151)

fix: replace youtube embeds with youtube-nocookie

---

game/static/game/js/level_editor.js

This change fixes #1152 .  The function setUpTrashcan() in level_editor.js was previously only setting the location of the trash on a window resize.  This change ensures it is set also when the page is first loaded.
Manually, in Chrome 88.0.4324.146 on Ubuntu 20.04
On first load:
On window resize:
- [ x ] I have linked this PR to a Zenhub Issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1160)

fix: set location of trash can on first render

---

game/static/game/js/game.js

When muting the game, the cookie should only be set if the user gave consent for functional cookies. Muting the game should still work, but the status won't be saved on page reload or other levels if the cookie is not set.
1. Change cookie settings to allow functional cookies, then mute the game and either refresh the page or go to another level. The game should still be muted.
2. Change cookie settings to disallow functional cookies, then mute the game and either refresh the page or go to another level. The game should not be muted anymore as the status has not been saved. However, toggling the mute button should work while on the page (until reloading).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

feat: check cookie consent when muting game

---

game/end_to_end_tests/base_game_test.py
game/end_to_end_tests/data/blockly_solutions/once_forwards.xml
game/end_to_end_tests/test_level_failures.py
game/end_to_end_tests/test_level_win.py
game/end_to_end_tests/test_localstorage.py
game/end_to_end_tests/test_play_through.py
game/static/game/js/blocklyControl.js
game/static/game/js/pythonControl.js
game/templates/game/game.html

- Disable browser local storage if the user is not logged in by passing logged in status to the blockly controller and python controller, which save to localstorage only if the user is logged in.  
- Disable save and load buttons in the game template when user is not logged by change to template
- Refactor base_game_test.py : move method complete_and_check level up from test_run_through.py
- Added new test file test_localstorage.py with 2 selenium tests: if logged in, data should be saved to localstorage, if not then not saved. These new tests include new test functionality that allow adding an xml solution to a workspace in Blockly.  - Tested by hand
- Verified that unit tests run (on MacOS 11.5.1 and Chrome Version 92.0.4515.131 (Official Build) (arm64)
- [ x ] My change requires a …

fix: disable saving and loading of workspace when user is not logged in

---

game/static/game/css/level_moderation.css
game/static/game/css/level_selection.css
game/static/game/js/level_moderation.js
game/templates/game/level_moderation.html

Fix for #1099: no modal appeared when you select delete for a level in the level moderation page. Added the required element to the page and the javascript.  It looks as though this is the only place it is needed in RR so have kept it local to that page, and we can refactor if it is also needed elsewhere.  
Unit and end-to-end tests run.  No new tests added because it's a bug fix and functionality unchanged.  Verified by hand (Mac OS, Chrome 92)
- [ / ] I have linked this PR to a Zenhub Issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1229)

fix: 1099 cannot delete custom levels in level moderation page

---

game/views/level_editor.py
game/views/level_moderation.py
game/views/scoreboard.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1256)

fix: fix issue with deleted students appearing

---

game/static/game/css/level_selection.css
game/static/game/css/scoreboard.css
game/templates/game/level_selection.html
game/templates/game/scoreboard.html
game/tests/test_scoreboard.py
game/views/scoreboard.py
game/views/scoreboard_csv.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279)

fix: Make Scoreboard logic more efficient

---

game/end_to_end_tests/selenium_test_case.py
game/static/game/js/model.js
game/static/game/js/program.js
game/templates/game/level_selection.html
game/views/level.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1280)

fix: Create failed attempt on crash, out of fuel and red light events

---

.github/workflows/ci.yml
.github/workflows/publish-python-package.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1299)

fix: publish

---

game/tests/test_scoreboard.py
game/views/scoreboard.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1315)

fix: Show default data on student scoreboard

---

game/end_to_end_tests/selenium_test_case.py
rapid_router_test_settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1325)

fix: use a non threaded server in SeleniumTestCase

---

.github/workflows/ci.yml
Pipfile.lock
game/static/game/js/level_editor.js
game/views/level_editor.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1372)

fix: Fix custom level save bugs

---

game/migrations/0081_first_12_levels_no_algo_score.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1419)

fix: Fix migration 81

---

game/end_to_end_tests/base_game_test.py
game/end_to_end_tests/test_level_selection.py
game/static/game/css/level_selection.css
game/static/game/js/level_selection.js

Bug fix for #1393 : when an episode is complete, the coin shows in rapid router levels view as broken image.
Added new end to end test for level selection.
- [  x ] My change requires a change to the documentation.
- [  x ] I have updated the documentation accordingly.
- [  / ] I have linked this PR to a ZenHub Issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1425)

fix: broken coin image for students in episode

---

game/messages.py

fixes: #1198
Added ',' after 'Blockly' in the level description
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1474)

fix(messages): Improve the readability of the description of the levels

---

game/messages.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1499)

fix: Update level 39 hint

---

game/messages.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1517)

fix: Typo in description of 109

---

game/end_to_end_tests/test_play_through.py
game/static/game/js/blocklyCompiler.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1524)

fix: Compile cow block properly

---

game/messages.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1525)

fix: level 36 message

---

.github/workflows/publish-python-package.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1553)

ci: Replace Razbot with CFLbot

---

game/static/game/js/blocklyControl.js

- This is a fix to this [issue](https://github.com/ocadotechnology/rapid-router/pull/1566).
- It was done by always moving the start block to the fixed position (100, 100) (instead of the previous behavior of generating it in random positions based on the variable `i`, which is a global variable that changes by the for loops inside the code).
[Screencast from 14-01-24 09:19:29.webm](https://github.com/ocadotechnology/rapid-router/assets/68364202/cd22e23f-bf0d-4b42-8b33-9aaa3eb587ef)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1568)

fix: 1563-Start Block Is Not Generated At The Top Left Of The Window #1566

---

game/messages.py
game/migrations/0087_rename_episodes.py
game/migrations/0088_rename_episodes.py
game/templates/game/level_selection.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)

fix: rename episodes and levels

---

Pipfile.lock
game/level_management.py
game/messages.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1608)

fix: move level creation email to dotdigital

---

game/static/game/js/level_editor.js

As described in Stefan's comment, scenery items can now be dragged off the grid to the bin to be removed. If they are dragged off the grid but are not released over the bin, they will snap back to the grid (i.e. if the scenery item's x value is too large such that it's off the grid when it's released, it will automatically snap back to the max x value so that it's on the grid).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1616)

fix: allow scenery to be dragged to bin

---

game/static/game/js/blockly/msg/js/en-gb.js
game/static/game/js/blockly/msg/js/en.js
game/static/game/js/blockly/msg/js/fr.js
game/static/game/js/blockly/msg/js/hi.js
game/static/game/js/blocklyCustomBlocks.js

The "do" block was translated as part of the "repeat until / do" and "repeat while / do", so I have taken the translations from there. I have also now added this specific "do" to the translations doc for future languages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1623)

fix: add do translation

---

Pipfile.lock
game/static/game/js/model.js

I added a popup for when a delivery is made at a location which is not a valid destination. This popup informs the user that 
they tried to deliver at a destination that doesn’t exist. The failure sound now plays when this popup appears and this event is logged as a reason for termination when it occurs.
I tested this using pytest. It passed all 58 tests. The selenium tests did not run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1694)

fix: Deliver at non-destination does not show popup

---

game/migrations/0100_reorder_python_levels.py

This PR fix addresses an issue where Episode 15 (Python Den) was still marked as being in development, so any user who didn't have early access wasn't able to see it or the following Python Den levels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1709)

fix: fix episode 15

---

Pipfile
Pipfile.lock
example_project/rapid_router_test_settings.py
example_project/settings.py
game/templates/game/base.html
game/urls.py
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1714)

fix: Django js reverse upgrade

---

game/messages.py
game/templates/game/level_selection.html

The following links have been fixed:
- the link in some Python Den levels' hints (i.e. Level 42's hint) to the full list of Python commands
- the "You can read more about Blockly here" link on the Rapid Router level selection page 
- the "You can read more about Python here" link on the Rapid Router level selection page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1721)

fix: update broken python and blockly documentation links

---

game/static/game/js/level_selection.js
game/templates/game/level_selection.html
game/views/level_selection.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1745)

fix: Remove old Python levels redirect

---

Pipfile
Pipfile.lock
example_project/urls.py
game/end_to_end_tests/selenium_test_case.py
game/python_den_urls.py
game/templates/game/scoreboard.html
game/theme.py
game/urls.py
setup.py

- Upgraded all Django-related libraries, and removed the ones that are now installed directly by the common package.
- Updated all URLs to use `re_path` instead of `url`
- Replaced `ifnotequal` with simply `if !=`
- Replaced `ugettext` with `gettext`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1748)

feat!: Django 4

---

game/static/game/js/level_editor.js

I fixed the issue where a character change in the level editor would not appear in the character tab and would default to the van option. 
This happened because the restoreState function was trying to get the character id from saved level, but it was the character name that was saved not the id. I changed this by getting the character id from the saved character name.
I tested this using pytest and all the tests passed. 
I also tested it by creating new levels in the level editor and checking if the change is there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1749)

fix: character change does not persist after save.

---

game/static/game/js/level_editor.js

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1752)

fix: invalid cow squares remain highlighted

---

game/templates/game/python_den_level_selection.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1759)

fix: worksheet counter and accordion arrows
