ocadotechnology/rapid-router

- game/app_settings.py
- game/views/level.py
- game/views/level_selection.py
Part of #688
This will need ocadotechnology/codeforlife-portal#145 to be merged for proper deployment.
> Remove references to portal.beta, replace with custom settings.

- game/static/game/js/level_editor.js
- game/static/game/js/messages.js
So in Create mode: I changed the wording in the hint, and added an error when trying to play without a road.
> Added hints to create road first, error when no road #506

- MANIFEST.in
- setup.cfg
- setup.py
- versioneer.py
This is needed for the new deployment infrastructure
> Fix the packaging of wheels

- game/forms.py
- game/messages.py
- game/static/game/css/scoreboard.css
- game/static/game/css/settings.css
- game/templates/game/logged_students.html
- game/views/helper.py
If/when we implement avatars, this can be reintroduced. At the moment it's just dead code
> Remove unused avatar code

- game/tests/test_api.py
These are a few examples of the kinds of test we can write for #593. I thought it would be good to create just a few tests first and discuss what kind of testing we actually want to do, before trying to achieve full coverage. Most of the APIs are quite straight-forward, so I wasn't sure how repetitive we wanted to make the tests.
I also wasn't entirely certain how much we should rely on data existing in the database during the tests. I guess the alternative would be inserting and deleting some test data just for the test?
> Add example tests for REST API

- .travis.yml
- run
Looks like crowdin doesn't support the wrapped lines, so change
how the lines are generated.
> Provide a crowdin compatible file. Fixes #754

- game/templates/game/game.html
- game/templates/game/level_selection.html
#760 A few hardcoded strings wrapped with gettext.
> Add missing translations

- game/templates/game/scoreboard.html
- game/views/level_moderation.py
- game/views/scoreboard.py
- game/views/scoreboard_csv.py
#760 A few hardcoded strings wrapped with gettext.
> Missing translations

- game/templates/game/scoreboard.html
- game/views/scoreboard.py
- game/views/scoreboard_csv.py
By replacing ugettext with ugettext_lazy #768 should be fixed.
> ugettext replaced with ugettext_lazy in scoreboard

- game/serializers.py
- game/tests/test_api.py
- game/theme.py
- game/views/api.py
> get themes in API - Fixes #767

- .eslintrc
- .travis.yml
- game/static/game/js/game.js
- game/static/game/js/level_moderation.js
- game/templates/game/base.html
- game/templates/game/basenonav.html
- game/urls.py
- run
> Add javascript translation support

- README.md
- game/autoconfig.py
- game/templates/game/crowdin.html
Working around https://github.com/ocadotechnology/rapid-router/issues/759#issuecomment-219317777
> Switch translation language to `lol-us`

- game/templates/game/game.html
> Filter lesson description using escapejs

- README.md
- run
This will allow the game to run without all devs having to install the
libraries required to work on the translation/localisation
> MakeTranslationSetupOptional

- game/static/game/js/game.js
- game/static/game/js/messages.js
- game/static/game/js/tab.js
> Add missing translations && refactoring in tabs

- game/static/game/js/blocklyCustomBlocks.js
> Externalize strings used in custom blockly blocks

- game/static/game/image/actions/go.svg
Changed from ‘Go’ to an play icon. @piotrrepetowski
> Updated go button Fixes #790

- game/messages.py
No 'ice' visible in the level. It is the first pure Python level with multiple possible routes.
> Changed level94 title to something more appropriate

- game/templates/game/game.html
- game/templates/game/level_editor.html
- game/templatetags/game/utils.py
JSON is moved to HTML data-* attributes which allows them to be escaped
fully.
Also now using Django's built-in filters wherever possible (especially
in preference to doing checks within JS). Helps with readability and
reliability (eg: differentiating the string "None" and value None).
distinguishable from a variable which is None.
> Remove XSS vulnerabilities in the game.html model.

- game/views/level_editor.py
If you were a teacher not in a school, it would show you all the other teachers that were also not in schools.
> Bug fixed, no longer displays all teachers

- game/templates/game/level_moderation.html
- game/templates/game/scoreboard.html
> Loading order of scripts changed on level moderation and scoreboard

- game/tests/test_level_editor.py
- game/tests/utils/__init__.py
- game/tests/utils/level.py
- game/tests/utils/teacher.py
Tests teachers cannot share with the wrong other teachers. 
Closes issue #818
> Tests level sharing

- game/end_to_end_tests/data/blockly_solutions/crash_going_forward_on_left_turn.xml
- game/end_to_end_tests/data/blockly_solutions/crash_going_forward_on_right_turn.xml
- game/end_to_end_tests/test_crashes.py
- game/tests/test_random_road.py
- Random road tests check if the generated road corresponds to the size, branchiness, traffic lights/scenery (on/off) parameters.
- Van crashes tests now test crashes from every possible direction.
> More tests!

- .travis.yml
- test_settings.py
This makes the tests runtime a lot quicker (see issue #847 for more details).
> Travis now uses Chromedriver.

- setup.py
explicitly adding pytz in the project
> trying to solve timezone error in gae

- setup.py
This reverts commit 94d5ee97cadce9231916e1f8c55b8bb7a5a191e7.
> Revert "trying to solve timezone error in gae"

- README.md
Added instructions on how to deal with common problem with `mkvirtualenv` and `workon` commands missing after installing `virtualenvwrapper`.
> Added virtualenvwrapper troubleshooting to README.md

- game/static/game/js/level_editor.js
- game/views/level_editor.py
Input for custom level name undergoes validation.
> Fix level editor save level issue

- game/tests/test_level_editor.py
- game/tests/test_level_moderation.py
Renamed field IDs to match ones in portal.
> Fixes broken tests

- README.md
> Updating contributing guidelines

- README.md
@charafau has helped clarify the Ruby version requirements for the sass dependency. This PR is to update the README with what he found out.
> Update ruby version documentation in README

- game/forms.py
- game/static/game/css/level_selection.css
- game/static/game/js/levelSelection.js
- game/templates/game/base.html
- game/templates/game/level_moderation.html
- game/templates/game/level_selection.html
Still working on the scoreboard on an other branch. This is to fix the newsletter link at the bottom and to switch to new style as requested in issue #956
> migrate to new style apart from scoreboard page

- game/static/game/js/drawing.js
- game/static/game/js/game.js
- run
The bug was due to two event listeners listening for the same "pan" event. The mouse "pan" event only happens on the game and not the level creator now as you need to click and drag to create roads
> Fix level creator not working due to an overriding event listener

- game/static/game/js/level_moderation.js
- game/templates/game/level_moderation.html
- Fixed JavaScript syntax to fix the level moderation issue.
- Moved JavaScript from the html template into the JS file.
> Fixes level moderation page

- game/views/level_selection.py
- game/views/scoreboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/994)
> using new localisation friendly function to populate the scoreboard

- game/migrations/0069_fix_episodes_order_part_2.py
- game/tests/migrations/base_test_migration.py
- game/tests/migrations/test_migration_fix_episodes_order.py
- game/views/level_selection.py
- Added migration to grab levels by name manually and inputting them in the correct episode.
- Added a migration test for the latest migrations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1005)
> Gets correct levels for episodes 7 and 8

- game/messages.py
For consistency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1015)
> Removed full stops and added spaces

- game/static/game/js/game.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1031)
> fix: use single quotes

- game/end_to_end_tests/base_game_test.py
- game/end_to_end_tests/editor_page.py
- game/end_to_end_tests/test_level_editor.py
- game/templates/game/level_editor.html
- game/views/level_editor.py
The level editor wasn't working after the Django upgrade, this fixes it.
A Selenium test was added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1034)
> fix: make level editor work again

- .codecov.yml
- .travis.yml
Coveralls was replaced by codecov for code coverage analysis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1039)
> feat: added codecov config

- game/templates/403.html
- game/templates/404.html
- game/templates/500.html
- game/templates/game/basenonav.html
- game/templates/game/game.html
- game/templates/game/level_moderation.html
- game/templates/game/level_selection.html
Removed some extra blank lines in the template files.
This PR is prefixed with *fix* to account for the release that should have happened at the previous PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1050)
> fix: remove extra blank lines in templates

- .github/ISSUE_TEMPLATE/new_task.md
Added the "Copywrite Requirements" optional section on GitHub's new task template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1052)
> docs: add copywrite requirements to new task template

- CONTRIBUTING.md
- Pipfile.lock
This PR fixes a typo in the contributing docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1075)
> fix: Fix typo in contributing docs

- Pipfile.lock
- game/tests/test_level_editor.py
- game/tests/test_level_moderation.py
- setup.py
Removed `django-jquery` dependency, as it isn't used or maintained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1077)
> fix: remove django jquery

- game/autoconfig.py
- game/static/game/sass/_mixins.scss
- game/static/game/sass/game.scss
- setup.py
Signed-off-by: Niket Shah <masterniket@gmail.com>
Django bourbon seems like it was used in some dead code that was not deleted at the time we removed django-nuit from the project.
- Visually inspected game (manually tested visual changes)
- Ran tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1082)
> fix: remove django bourbon

- .travis.yml
- game/tests/test_api.py
- game/tests/utils/user.py
- game/views/api.py
This PR make the API URLs require admin login.
API tests have been run successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1086)
> fix: Make API URLs secure

- README.md
- docs/life_cycle_of_a_code_change.md
This PR adds a doc explaining the life cycle of a code change.
It also updates the coverage badge to be the CodeCov one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1088)
> docs: Add life cycle of a code change doc

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1094)
> fix: Install latest version of semantic release

- game/models.py
- game/serializers.py
- game/views/scoreboard.py
Manually and with unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1098)
> fix: Replace __unicode__ with __str__ in models

- game/templates/game/base.html
- game/templates/game/scoreboard.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1100)
> fix: Link to correct CSS file instead of JS file

- game/views/level_editor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1104)
> fix: Add authentication class to views

- game/messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1107)
> fix: Remove link to bad website

- game/end_to_end_tests/base_game_test.py
- game/static/game/js/level_editor.js
- game/tests/test_level_editor.py
- game/tests/test_level_moderation.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1108)
> fix: Update not logged in links

- game/tests/test_level_editor.py
- game/tests/test_level_moderation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1109)
> fix: Fix teacher login in tests

- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)
> fix: Remove six

- .travis.yml
- game/end_to_end_tests/game_page.py
- game/static/game/css/game_screen.css
- game/static/game/js/drawing.js
- game/static/game/js/game.js
- game/static/game/sass/_variables.scss
- game/static/game/sass/game.scss
- game/templates/game/basenonav.html
Signed-off-by: Niket <niket.shah1@ocado.com>
Removed the javascript part of foundation as it required an older version of jquery we will no longer use. The only thing that we used foundation js for was to show the modal with animation. This has been implemented using html/css.
I have also reformatted the files I have edited to be more in line with our other Code for Life projects.
Manual test and UX review. Ran through jquery migration tool. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1127)
> fix: Remove foundation and reimplement modal in RR

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- rapid_router_test_settings.py
Build (and testing) now happens in GitHub actions when a PR is open.
Make sure the GitHub action is triggered on PR and check if the build, including running tests, is successful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1133)
> ci: GitHub actions build

- .github/workflows/ci.yml
- .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1136)
> fix: Use Github Actions to publish rapid-router to PyPi

- .github/workflows/ci.yml
Fixed codecov issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1142)
> ci: fix codecov

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1147)
> fix: Move autoconfig installation to Pipfile

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1148)
> fix: Remove build dependencies

- Pipfile
- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1150)
> fix: Move autoconfig back to Pipfile

- game/static/game/js/level_editor.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1171)
> fix: Improve sharing table generation

- game/views/level.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1174)
> fix: require post

- game/messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203)
> fix: add hint text for RR lv 80 onwards

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1214)
> docs: a small readme fix

- Pipfile.lock
- game/tests/test_level_editor.py
- game/tests/test_level_moderation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1215)
> fix: Remove captha from tests

- game/static/game/css/level_selection.css
- game/static/game/js/scoreboard.js
- game/templates/game/base.html
- game/templates/game/level_moderation.html
- game/templates/game/level_selection.html
- game/templates/game/scoreboard.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1217)
> feat: rebranding changes

- game/templates/game/base.html
- game/templates/game/level_moderation.html
- game/templates/game/level_selection.html
- game/templates/game/scoreboard.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1222)
> fix: table and button updates

- game/templates/game/basenonav.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1223)
> fix: Extend base.html instead of old base

- game/templates/game/base.html
- game/templates/game/level_selection.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1231)
> fix: header updates

- game/templates/game/base.html
A small fix for the RR levels page header
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1232)
> fix: RR level header fix

- game/templates/game/base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1254)
> fix: remove sticky subnav from RR

- game/csp_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1258)
> fix: Add progress bar stylesheet to CSP config

- game/templates/game/base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1265)
> fix: align header

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1268)
> fix: Upgrade Django to 2.2.25

- game/views/scoreboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1273)
> fix: student scoreboard see all levels

- game/static/game/css/scoreboard.css
- game/static/game/js/scoreboard.js
- game/templates/game/scoreboard.html
Fixes bugs rows 39, 40 and 41 in bugs spreadsheet and also part of bug row 32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1277)
> fix: Scoreboard select all boxes, dropdown styles and text spacing

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1283)
> fix: Upgrade Django to 2.2.26

- game/static/game/css/dataTables.custom.css
- game/templates/game/scoreboard.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1285)
> fix: remove black borders from level moderation and scoreboard

- game/static/game/js/level_moderation.js
- game/tests/test_level_moderation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1287)
> fix: delete level on moderate page

- game/static/game/css/game.css
- game/templates/game/game.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1288)
> fix: scrollbar for Python pane

- game/static/game/css/game.css
- game/static/game/js/game.js
- game/templates/game/game.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1289)
> feat: resize python window

- .github/workflows/ci.yml
- .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1303)
> fix: revert previous ci changes

- .github/workflows/ci.yml
- .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1304)
> fix: trim ci flow

- game/csp_config.py
Add Crowdin CDN url to the CSP configuration to allow the script to work.
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1311)
> fix: Add Crowdin CDN to CSP config

- game/csp_config.py
Allow Crowdin in-context translation resources
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1312)
> fix: Allow Crowdin in-context translation resources

- game/static/game/js/game.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1314)
> fix: fix freeze issue with fast button

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1321)
> fix: cleanup ci and update pipfile

- game/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1322)
> fix: remove cache_page

- game/level_management.py
- game/tests/test_level_editor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1326)
> fix: hide shared levels of anonymised users

- game/static/game/js/blocklyControl.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)
> fix: fixed the start block appearing in the bin 

- game/csp_config.py
- game/templates/game/scoreboard.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1345)
> fix: Upgrade JqueryUI to 1.13.1

- .codecov.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1348)
> build: Make CodeCov requirement 90%

- game/static/game/sass/game.scss
- game/templates/game/basenonav.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1352)
> feat: Screentime warning

- .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1355)
> fix: Fix version of semantic-release to avoid bug

- game/forms.py
- game/permissions.py
- game/static/game/js/level_moderation.js
- game/tests/test_level_moderation.py
- game/views/level_moderation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358)
> feat: include students from other classes in level moderation for admin teachers

- game/static/game/css/game.css
- game/static/game/css/game_screen.css
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1363)
> fix: adjust alignment

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- game/static/game/js/game.js
- game/static/game/js/level_editor.js
- game/templates/game/game.html
- game/templates/game/scoreboard.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369)
> fix: Resolve scoreboard and button issues

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- game/permissions.py
- game/static/game/css/level_share.css
- game/static/game/js/sharing.js
- game/templates/game/level_editor.html
- game/templates/game/level_selection.html
- game/tests/test_level_editor.py
- game/tests/test_level_moderation.py
- game/tests/test_level_selection.py
- game/tests/utils/teacher.py
- game/views/level_editor.py
- game/views/level_selection.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1371)
> feat: Admin power for custom levels

- game/static/game/css/game.css
- game/static/game/css/game_screen.css
- game/static/game/css/skulpt/codemirror.css
- game/static/game/js/game.js
- game/static/game/js/skulpt/codemirror.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1373)
> fix: fix certain elements about the UI to an acceptable standard

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1377)
> fix: Update Django to 3.2.16

- game/static/game/css/game_screen.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1381)
> fix: Padding in level editor

- game/static/game/js/animation.js
- game/static/game/js/game.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1388)
> fix: added title case to level buttons

- Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1392)
> build: Upgrade certifi

- .github/workflows/ci.yml
- .github/workflows/publish-python-package.yml
- .github/workflows/semantic-pull-request-check.yml
- .github/workflows/snyk.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1399)
> build: Update Github actions

- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1406)
> build: Remove future from dependencies

- Pipfile.lock
- game/random_road.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1408)
> fix: Remove use of old_div

- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1417)
> fix: Patch update for more-itertools

- Pipfile.lock
- game/messages.py
- game/views/level.py
- game/views/level_moderation.py
- game/views/scoreboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1421)
> feat: Update episode videos

- Pipfile.lock
- game/forms.py
- game/templates/game/scoreboard.html
- game/tests/test_scoreboard.py
- game/views/scoreboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1422)
> fix: Custom levels always have max score of 10

- game/static/game/css/game.css
- game/static/game/js/drawing.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1424)
> fix: Move zoom buttons and fix default zoom factor

- game/static/game/css/level_editor.css
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1438)
> fix: make sidebar green same as the main game one

- .github/workflows/ci.yml
- .github/workflows/publish-python-package.yml
- .github/workflows/snyk.yaml
- Pipfile
- Pipfile.lock
- setup.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1462)
> feat: Upgrade Python to 3.8

- .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1469)
> build: Set semantic release < 8

- game/messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1501)
> fix: Update level 47 title

- game/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1508)
> fix: exclude coming soon levels

- Pipfile.lock
- game/tests/test_level_moderation.py
- game/tests/utils/teacher.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1527)
> fix: Revert Django to 3.2.22 (CI/CD measuring)

- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1530)
> fix: Update Django to 3.2.23 (CI/CD measuring)

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1531)
> build: Downgrade Django (CI/CD measuring)

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1532)
> fix: Upgrade Django to 3.2.23 again (CI/CD measuring)

- .codecov.yml
- game/static/game/css/game_screen.css
- game/static/game/js/drawing.js
- game/static/game/js/level_editor.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1539)
> fix: Buttons in level editor popup

- .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1557)
> ci: Remove Crowdin action again

- game/messages.py
Fix: the name of level 36 from "What else? If-else, that's what!" to "What else? If-else if-else, that's what!"
I tested it myself the changes in browser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1560)
> fix: level 36

- game/migrations/0090_add_missing_model_solutions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1587)
> fix: Only target recent attempts

- game/messages.py
- game/views/level_solutions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1595)
> fix: change n to number in levels 106-109

- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1601)
> fix: Upgrade libsass

- example_project/rapid_router_test_settings.py
- example_project/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1605)
> build: Enable atomic transactions

- game/static/game/js/animation.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1618)
> fix: prevent character from driving over trees in level 36

- game/end_to_end_tests/editor_page.py
- game/end_to_end_tests/test_level_editor.py
- game/static/game/css/game_screen.css
- game/static/game/js/level_editor.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634)
> feat: make scenery decor draggable

- game/static/game/js/game.js
- game/views/level.py
This PR fixes:
- the bug that overwrote default level descriptions/hints with the default level description/hint
- the bug that added extra line breaks to the default level starting popup text
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1657)
> fix: fix bug with default level description/hint and formatting

- .github/workflows/ci.yml
- .github/workflows/publish-python-package.yml
- .github/workflows/semantic-pull-request-check.yml
- .github/workflows/snyk.yaml
- Pipfile
- Pipfile.lock
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1713)
> fix: Upgrade to Python 3.12

- game/tests/test_level_selection.py
- game/views/level.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1722)
> fix: Use correct level name limit for next level URL

- game/migrations/0101_rename_episodes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1723)
> fix: Rename old coming soon episodes

- game/templates/game/base.html
- game/templates/game/basenonav.html
Feel free to use this PR for anything related to SEO/tidying Python Den (codeforlife-portal #2343)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1728)
> fix: tidy Python Den

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/new_task.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1734)
> docs: Add section to issue templates for code guidance

- game/migrations/0001_squashed_0025_levels_ordering_pt1.py
- game/migrations/0100_reorder_python_levels.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1735)
> fix: migrations

- game/templates/game/base.html
- game/templates/game/level_moderation.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1744)
> fix: broken level moderation JS

- game/static/game/js/level_editor.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1755)
> fix: Disallow special characters for custom level fields

- game/templates/game/python_den_level_selection.html
- game/views/level_selection.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1763)
> fix: worksheet index

- game/views/level_editor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1767)
> fix: non school teachers can now save levels

- game/static/game/css/game.css
- game/static/game/js/pythonControl.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1769)
> fix: error messages

- Pipfile.lock
- game/admin.py
- game/messages.py
- game/migrations/0116_update_worksheet_video_links.py
- game/static/game/js/drawing.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1779)
> fix: Use Gitbook videos instead of YouTube links

- Pipfile.lock
- game/permissions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1782)
> fix: permissions

- game/messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1783)
> fix: add deliver command

- .github/workflows/ci.yml
- .github/workflows/publish-python-package.yml
- .github/workflows/snyk.yaml
- Pipfile
- Pipfile.lock
- example_project/rapid_router_test_settings.py
- example_project/settings.py
- manage.py
- run
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1786)
> ci: Implement new Snyk checks

- game/messages.py
- game/static/game/css/game_screen.css
- game/static/game/js/drawing.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1789)
> fix: Use video instead of iframe in popup

- Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1796)
> feat: django 5.2

- Pipfile.lock
- example_project/rapid_router_test_settings.py
- example_project/settings.py
- game/end_to_end_tests/test_level_selection.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1797)
> fix: new common

- Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1798)
> fix: drf 3.16

- Pipfile.lock
- example_project/rapid_router_test_settings.py
- example_project/settings.py
- game/templates/game/basenonav.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/rapid-router/1804)
> fix: sass compiler
